<Project Sdk="Microsoft.NET.Sdk.Razor">
  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="bunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\PoRedoMedia.Api\PoRedoMedia.Api.csproj" />
    <ProjectReference Include="..\..\src\PoRedoMedia.Client\PoRedoMedia.Client.csproj" />
    <ProjectReference Include="..\..\src\PoRedoMedia.Shared\PoRedoMedia.Shared.csproj" />
  </ItemGroup>
</Project>
